import { Message, GuildMember, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, PermissionFlagsBits } from 'discord.js'
import { t } from '../i18n'
import { askAI, heroPickPrompt } from '../ai'

// Dota 2 roles per slot index (0-4 = team A, 5-9 = team B)
const ROLES = ['Hard Carry', 'Mid Lane', 'Offlane', 'Soft Support', 'Hard Support']

// Hero roles preferred for each Dota 2 position (in priority order)
const ROLE_PREFERRED_HERO_ROLES: Record<string, string[]> = {
  'Hard Carry':   ['Carry'],
  'Mid Lane':     ['Carry', 'Nuker', 'Escape'],
  'Offlane':      ['Durable', 'Initiator', 'Disabler'],
  'Soft Support': ['Support', 'Disabler', 'Initiator'],
  'Hard Support': ['Support'],
}

export interface Group {
  size: 2 | 4 | 5
  creatorId: string
  creatorName: string
  members: { id: string; name: string }[]
  channelId: string
  messageId?: string
}

// One active group per guild channel (keyed by channelId)
const activeGroups = new Map<string, Group>()

// Stores the last randomized teams per channel — used by the Move/Assign-Heroes buttons
interface StoredTeams {
  teamA: { id: string; name: string }[]
  teamB: { id: string; name: string }[]
  usedHeroIds?: number[]
  autoGroup?: {
    sourceVoiceChannelId: string
    excludedIds: string[]
  }
}
const lastTeams = new Map<string, StoredTeams>()

// Tracks re-roll votes per channel — needs at least 1 vote from each team
interface RerollVotes {
  teamA: Set<string>  // user IDs
  teamB: Set<string>
}
const rerollVotes = new Map<string, RerollVotes>()

// Stores teams generated by !autox waiting for the trigger user to confirm
interface PendingAutoGroup {
  size: 2 | 4 | 5
  candidates: { id: string; name: string }[]
  teamA: { id: string; name: string }[]
  teamB: { id: string; name: string }[]
  triggerUserId: string
  sourceVoiceChannelId: string
  excludedIds: string[]
}
const pendingAutoGroups = new Map<string, PendingAutoGroup>()

export class GroupHandler {
  // ─── !x2 / !x4 / !x5 ────────────────────────────────────────────────────
  static async startOrJoin(message: Message, size: 2 | 4 | 5) {
    const channelId = message.channel.id
    const existing = activeGroups.get(channelId)

    if (existing) {
      // Trying same size → join
      if (existing.size !== size) {
        message.reply(t('group.alreadyExists', { size: existing.size }))
        return
      }
      return GroupHandler._addMember(message, existing)
    }

    // Create new group
    const group: Group = {
      size,
      creatorId: message.author.id,
      creatorName: message.member?.displayName ?? message.author.username,
      members: [{ id: message.author.id, name: message.member?.displayName ?? message.author.username }],
      channelId,
    }
    activeGroups.set(channelId, group)
    console.log(`[GroupHandler] New x${size} group created by ${group.creatorName}`)
    await GroupHandler._sendGroupStatus(message.channel, group)
  }

  // ─── join an existing group ───────────────────────────────────────────────
  private static async _addMember(message: Message, group: Group) {
    const totalSlots = group.size * 2
    const alreadyIn = group.members.some((m) => m.id === message.author.id)
    if (alreadyIn) {
      message.reply(t('group.alreadyIn'))
      return
    }
    if (group.members.length >= totalSlots) {
      message.reply(t('group.groupFull'))
      return
    }
    const displayName = message.member?.displayName ?? message.author.username
    group.members.push({ id: message.author.id, name: displayName })
    console.log(`[GroupHandler] ${displayName} joined x${group.size} group`)

    if (group.members.length === totalSlots) {
      await GroupHandler._sendFullGroup(message.channel, group)
    } else {
      await GroupHandler._sendGroupStatus(message.channel, group)
    }
  }

  // ─── !x2leave / !x4leave / !x5leave ────────────────────────────────────────
  static async leave(message: Message) {
    const group = activeGroups.get(message.channel.id)
    if (!group) {
      message.reply(t('group.noGroup'))
      return
    }

    const idx = group.members.findIndex((m) => m.id === message.author.id)
    if (idx === -1) {
      message.reply(t('group.alreadyIn'))
      return
    }

    const leaving = group.members[idx]
    group.members.splice(idx, 1)

    if (group.members.length === 0) {
      activeGroups.delete(message.channel.id)
      message.channel.send(t('group.disbanded.empty'))
      return
    }

    // If creator left, promote the next member
    let creatorNote = ''
    if (group.creatorId === leaving.id) {
      group.creatorId = group.members[0].id
      group.creatorName = group.members[0].name
      creatorNote = ' ' + t('group.promoted', { name: group.creatorName })
    }

    console.log(`[GroupHandler] ${leaving.name} left x${group.size} group`)
    await message.channel.send(t('group.left', { name: leaving.name }) + creatorNote)
    await GroupHandler._sendGroupStatus(message.channel, group)
  }

  // ─── !x4cancel / !x5cancel ───────────────────────────────────────────────
  static cancel(message: Message) {
    const group = activeGroups.get(message.channel.id)
    if (!group) {
      message.reply(t('group.noGroup'))
      return
    }
    if (group.creatorId !== message.author.id) {
      message.reply(t('group.notCreator'))
      return
    }
    activeGroups.delete(message.channel.id)
    console.log(`[GroupHandler] x${group.size} group cancelled by ${message.author.username}`)
    message.channel.send(t('group.cancelled', { name: message.member?.displayName ?? message.author.username }))
  }

  // ─── !x4kick / !x5kick <nickname> ────────────────────────────────────────
  static async kick(message: Message, partialName: string) {
    const group = activeGroups.get(message.channel.id)
    if (!group) {
      message.reply(t('group.noGroup'))
      return
    }
    if (group.creatorId !== message.author.id) {
      message.reply(t('group.notCreator'))
      return
    }
    const lower = partialName.toLowerCase()
    const target = group.members.find(
      (m) => m.id !== group.creatorId && m.name.toLowerCase().includes(lower)
    )
    if (!target) {
      message.reply(t('group.memberNotFound', { name: partialName }))
      return
    }
    group.members = group.members.filter((m) => m.id !== target.id)
    console.log(`[GroupHandler] ${target.name} kicked from x${group.size} group by creator`)
    message.channel.send(t('group.kicked', { name: target.name }))
    await GroupHandler._sendGroupStatus(message.channel, group)
  }

  // ─── Button interactions ──────────────────────────────────────────────────
  static async handleButton(interaction: any) {
    // Auto-preview buttons are sent via DM; the guild channel ID is embedded in the customId
    if (
      interaction.customId.startsWith('group_auto_confirm:') ||
      interaction.customId.startsWith('group_auto_reroll:') ||
      interaction.customId.startsWith('group_auto_cancel:')
    ) {
      const colonIdx = interaction.customId.indexOf(':')
      const action = interaction.customId.slice(0, colonIdx)
      const guildChannelId = interaction.customId.slice(colonIdx + 1)
      const pending = pendingAutoGroups.get(guildChannelId)

      if (!pending) {
        await interaction.reply({ content: t('group.noTeamData'), ephemeral: true })
        return
      }
      if (interaction.user.id !== pending.triggerUserId) {
        await interaction.reply({ content: t('group.autoPreviewOnlyCreator', { name: `<@${pending.triggerUserId}>` }), ephemeral: true })
        return
      }

      if (action === 'group_auto_confirm') {
        const { size, teamA, teamB, sourceVoiceChannelId, excludedIds } = pending
        activeGroups.set(guildChannelId, {
          size,
          creatorId: interaction.user.id,
          creatorName: interaction.user.username,
          members: [...teamA, ...teamB],
          channelId: guildChannelId,
        })
        lastTeams.set(guildChannelId, {
          teamA,
          teamB,
          usedHeroIds: [],
          autoGroup: { sourceVoiceChannelId, excludedIds },
        })
        pendingAutoGroups.delete(guildChannelId)

        await interaction.deferUpdate()
        await GroupHandler._disableButtons(interaction)

        const guildChannel = interaction.client.channels.cache.get(guildChannelId) as any
        if (!guildChannel) return

        const teamsEmbed = new EmbedBuilder()
          .setColor(0x3071f7)
          .setTitle(`🤖 Auto x${size}`)
          .addFields(
            { name: t('group.teamATitle'), value: teamA.map((m, i) => `${i + 1}. ${m.name}`).join('\n'), inline: true },
            { name: t('group.teamBTitle'), value: teamB.map((m, i) => `${i + 1}. ${m.name}`).join('\n'), inline: true }
          )
          .setFooter({ text: `!x${size}cancel | !x${size}kick <nick>` })

        const confirmRow = new ActionRowBuilder<ButtonBuilder>().addComponents(
          new ButtonBuilder()
            .setCustomId('group_assign_heroes')
            .setLabel(t('group.btnAssignHeroes'))
            .setStyle(ButtonStyle.Success),
          new ButtonBuilder()
            .setCustomId('group_split_channels')
            .setLabel(t('group.btnMoveChannels'))
            .setStyle(ButtonStyle.Secondary)
        )

        await guildChannel.send({ embeds: [teamsEmbed], components: [confirmRow] })
        return
      }

      if (action === 'group_auto_reroll') {
        const { size, candidates } = pending
        const totalSlots = size * 2
        const newShuffled = GroupHandler._shuffle([...candidates]).slice(0, totalSlots)
        pending.teamA = newShuffled.slice(0, size)
        pending.teamB = newShuffled.slice(size)

        const previewEmbed = new EmbedBuilder()
          .setColor(0xffa500)
          .setTitle(`👁️ Preview — Auto x${size}`)
          .setDescription(t('group.autoPreviewDescription'))
          .addFields(
            { name: t('group.teamATitle'), value: pending.teamA.map((m, i) => `${i + 1}. ${m.name}`).join('\n'), inline: true },
            { name: t('group.teamBTitle'), value: pending.teamB.map((m, i) => `${i + 1}. ${m.name}`).join('\n'), inline: true }
          )

        await interaction.update({ embeds: [previewEmbed], components: [GroupHandler._buildAutoPreviewRow(guildChannelId)] })
        return
      }

      if (action === 'group_auto_cancel') {
        pendingAutoGroups.delete(guildChannelId)
        const cancelledEmbed = new EmbedBuilder()
          .setColor(0x4f545c)
          .setTitle(t('group.autoPreviewCancelledTitle'))
          .setDescription(t('group.autoPreviewCancelledDescription'))
        await interaction.update({ embeds: [cancelledEmbed], components: [] })
        return
      }

      return
    }

    const channelId = interaction.channel?.id
    if (!channelId) return

    if (interaction.customId === 'group_join') {
      const group = activeGroups.get(channelId)
      if (!group) {
        await interaction.reply({ content: t('group.noGroup'), ephemeral: true })
        return
      }
      const totalSlots = group.size * 2
      if (group.members.some((m) => m.id === interaction.user.id)) {
        await interaction.reply({ content: t('group.alreadyIn'), ephemeral: true })
        return
      }
      if (group.members.length >= totalSlots) {
        await interaction.reply({ content: t('group.groupFull'), ephemeral: true })
        return
      }
      const displayName = interaction.member?.displayName ?? interaction.user.username
      group.members.push({ id: interaction.user.id, name: displayName })
      console.log(`[GroupHandler] ${displayName} joined x${group.size} group via button`)
      await interaction.deferUpdate()
      await GroupHandler._disableButtons(interaction)
      if (group.members.length === totalSlots) {
        await GroupHandler._sendFullGroup(interaction.channel, group)
      } else {
        await GroupHandler._sendGroupStatus(interaction.channel, group)
      }
      if (group.members.length === totalSlots) {
        await interaction.channel.send(t('group.joined', { name: interaction.member?.displayName ?? interaction.user.username }))
      }
      return
    }

    if (interaction.customId === 'group_random_teams') {
      const group = activeGroups.get(channelId)
      if (!group) {
        interaction.reply({ content: t('group.noGroup'), ephemeral: true })
        return
      }
      await interaction.deferUpdate()
      await GroupHandler._disableButtons(interaction)
      await GroupHandler._randomTeams(interaction, group)
      return
    }

    if (interaction.customId === 'group_random_teams_heroes') {
      const group = activeGroups.get(channelId)
      if (!group) {
        interaction.reply({ content: t('group.noGroup'), ephemeral: true })
        return
      }
      await interaction.deferUpdate()
      await GroupHandler._disableButtons(interaction)
      await GroupHandler._randomTeamsHeroes(interaction, group)
      return
    }

    if (interaction.customId === 'group_assign_heroes') {
      const stored = lastTeams.get(channelId)
      if (!stored) {
        interaction.reply({ content: t('group.noTeamData'), ephemeral: true })
        return
      }
      await interaction.deferUpdate()
      await GroupHandler._disableButtons(interaction)
      await GroupHandler._assignHeroesToTeams(interaction, stored.teamA, stored.teamB)
      return
    }

    if (interaction.customId === 'group_fearless_prompt') {
      const stored = lastTeams.get(channelId)
      if (!stored?.autoGroup) {
        await interaction.reply({ content: t('group.fearlessUnavailable'), ephemeral: true })
        return
      }

      await interaction.reply({
        content: t('group.fearlessPrompt'),
        components: GroupHandler._buildFearlessPromptRows([...stored.teamA, ...stored.teamB]),
        ephemeral: true,
      })
      return
    }

    if (interaction.customId === 'group_fearless_same') {
      const stored = lastTeams.get(channelId)
      if (!stored?.autoGroup) {
        await interaction.update({ content: t('group.fearlessUnavailable'), components: [] })
        return
      }

      await interaction.update({ content: t('group.fearlessWorkingSame'), components: [] })
      await GroupHandler._runFearlessDraft(interaction, stored)
      return
    }

    if (interaction.customId.startsWith('group_fearless_avoid_')) {
      const stored = lastTeams.get(channelId)
      if (!stored?.autoGroup) {
        await interaction.update({ content: t('group.fearlessUnavailable'), components: [] })
        return
      }

      const avoidMemberId = interaction.customId.replace('group_fearless_avoid_', '')
      const avoidedMember = [...stored.teamA, ...stored.teamB].find((member) => member.id === avoidMemberId)
      await interaction.update({
        content: t('group.fearlessWorkingAvoid', { name: avoidedMember?.name ?? 'player' }),
        components: [],
      })
      await GroupHandler._runFearlessDraft(interaction, stored, avoidMemberId)
      return
    }

    if (interaction.customId === 'group_reroll_heroes') {
      const stored = lastTeams.get(channelId)
      if (!stored) {
        await interaction.reply({ content: t('group.noTeamData'), ephemeral: true })
        return
      }

      const userId = interaction.user.id
      const inA = stored.teamA.some((m) => m.id === userId)
      const inB = stored.teamB.some((m) => m.id === userId)
      if (!inA && !inB) {
        await interaction.reply({ content: t('group.rerollNotInTeam'), ephemeral: true })
        return
      }

      // Initialise vote store if needed
      if (!rerollVotes.has(channelId)) {
        rerollVotes.set(channelId, { teamA: new Set(), teamB: new Set() })
      }
      const votes = rerollVotes.get(channelId)!
      if (inA) votes.teamA.add(userId)
      if (inB) votes.teamB.add(userId)

      // Check if at least 1 vote from each team
      if (votes.teamA.size >= 1 && votes.teamB.size >= 1) {
        rerollVotes.delete(channelId)
        await interaction.deferUpdate()
        await GroupHandler._disableButtons(interaction)
        await GroupHandler._assignHeroesToTeams(interaction, stored.teamA, stored.teamB)
      } else {
        // Show current vote status
        const votesA = votes.teamA.size
        const votesB = votes.teamB.size
        await interaction.reply({
          content: t('group.rerollVoted', { votesA: String(votesA), votesB: String(votesB) }),
          ephemeral: false,
        })
      }
      return
    }

    if (interaction.customId === 'group_split_channels') {
      const stored = lastTeams.get(channelId)
      if (!stored) {
        interaction.reply({ content: t('group.noTeamData'), ephemeral: true })
        return
      }
      await interaction.deferUpdate()
      await GroupHandler._disableButtons(interaction)
      await GroupHandler._splitVoiceChannels(interaction, stored.teamA, stored.teamB)
      // Clean up — the event has started, group and team data are no longer needed
      activeGroups.delete(channelId)
      lastTeams.delete(channelId)
      rerollVotes.delete(channelId)
      return
    }
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────

  private static async _sendGroupStatus(channel: any, group: Group) {
    const totalSlots = group.size * 2
    const spots = totalSlots - group.members.length
    const memberList = group.members.map((m, i) => `${i + 1}. ${m.name}`).join('\n')

    const embed = new EmbedBuilder()
      .setColor(0x5865f2)
      .setTitle(t('group.statusTitle', { size: group.size, current: group.members.length, total: totalSlots }))
      .setDescription(memberList || '...')
      .setFooter({ text: `${spots} spot(s) remaining | !x${group.size}` })

    const joinRow = new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId('group_join')
        .setLabel(t('group.btnJoin'))
        .setStyle(ButtonStyle.Primary)
    )

    await channel.send({ embeds: [embed], components: [joinRow] })
  }

  private static async _sendFullGroup(channel: any, group: Group) {
    const memberList = group.members.map((m, i) => `${i + 1}. ${m.name}`).join('\n')

    const embed = new EmbedBuilder()
      .setColor(0x00ff99)
      .setTitle(t('group.fullTitle', { size: group.size }))
      .setDescription(memberList)
      .setFooter({ text: '⬇️' })

    const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId('group_random_teams')
        .setLabel(t('group.btnRandomTeams'))
        .setStyle(ButtonStyle.Primary),
      new ButtonBuilder()
        .setCustomId('group_random_teams_heroes')
        .setLabel(t('group.btnRandomTeamsHeroes'))
        .setStyle(ButtonStyle.Success)
    )

    await channel.send({ embeds: [embed], components: [row] })
  }

  private static _shuffle<T>(arr: T[]): T[] {
    const a = [...arr]
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1))
      ;[a[i], a[j]] = [a[j], a[i]]
    }
    return a
  }

  /** Disables all buttons on the message that triggered this interaction. */
  private static _buildAutoPreviewRow(guildChannelId: string) {
    return new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId(`group_auto_confirm:${guildChannelId}`)
        .setLabel(t('group.btnConfirmTeams'))
        .setStyle(ButtonStyle.Success),
      new ButtonBuilder()
        .setCustomId(`group_auto_reroll:${guildChannelId}`)
        .setLabel(t('group.btnRerollTeams'))
        .setStyle(ButtonStyle.Primary),
      new ButtonBuilder()
        .setCustomId(`group_auto_cancel:${guildChannelId}`)
        .setLabel(t('group.btnCancelPreview'))
        .setStyle(ButtonStyle.Danger)
    )
  }

  private static async _disableButtons(interaction: any) {
    try {
      const disabled = interaction.message.components.map((row: any) =>
        new ActionRowBuilder<ButtonBuilder>().addComponents(
          row.components.map((btn: any) =>
            ButtonBuilder.from(btn.toJSON ? btn.toJSON() : btn).setDisabled(true)
          )
        )
      )
      await interaction.message.edit({ components: disabled })
    } catch { /* ignore — message may have been deleted */ }
  }

  private static _buildFearlessPromptRows(players: { id: string; name: string }[]) {
    const rows: ActionRowBuilder<ButtonBuilder>[] = [
      new ActionRowBuilder<ButtonBuilder>().addComponents(
        new ButtonBuilder()
          .setCustomId('group_fearless_same')
          .setLabel(t('group.fearlessSamePlayers'))
          .setStyle(ButtonStyle.Success)
      ),
    ]

    let currentRow = new ActionRowBuilder<ButtonBuilder>()
    for (const player of players) {
      if (currentRow.components.length === 5) {
        rows.push(currentRow)
        currentRow = new ActionRowBuilder<ButtonBuilder>()
      }

      currentRow.addComponents(
        new ButtonBuilder()
          .setCustomId(`group_fearless_avoid_${player.id}`)
          .setLabel(GroupHandler._truncateButtonLabel(player.name))
          .setStyle(ButtonStyle.Secondary)
      )
    }

    if (currentRow.components.length > 0) {
      rows.push(currentRow)
    }

    return rows
  }

  private static _truncateButtonLabel(label: string, maxLength = 80) {
    if (label.length <= maxLength) return label
    return `${label.slice(0, maxLength - 3)}...`
  }

  private static async _runFearlessDraft(
    interaction: any,
    stored: StoredTeams,
    avoidMemberId?: string
  ) {
    const channelId = interaction.channel?.id
    const currentPlayers = [...stored.teamA, ...stored.teamB]
    const teamSize = stored.teamA.length as 2 | 4 | 5
    if (!channelId || currentPlayers.length !== teamSize * 2) return

    let nextPlayers = currentPlayers

    if (avoidMemberId) {
      const avoidedPlayer = currentPlayers.find((member) => member.id === avoidMemberId)
      if (!avoidedPlayer) {
        await interaction.followUp({ content: t('group.noTeamData'), ephemeral: true })
        return
      }

      const sourceChannel = interaction.guild?.channels.cache.get(stored.autoGroup!.sourceVoiceChannelId) as any
      const currentIds = new Set(currentPlayers.map((member) => member.id))
      const excludedIds = new Set(stored.autoGroup!.excludedIds)
      const replacementPool = sourceChannel?.members
        ?.filter((member: GuildMember) =>
          !member.user.bot &&
          !excludedIds.has(member.id) &&
          member.id !== avoidMemberId &&
          !currentIds.has(member.id)
        )
        .map((member: GuildMember) => ({ id: member.id, name: member.displayName })) ?? []

      if (replacementPool.length === 0) {
        await interaction.followUp({
          content: t('group.fearlessNoReplacement', { name: avoidedPlayer.name }),
          ephemeral: true,
        })
        return
      }

      const replacement = GroupHandler._shuffle(replacementPool)[0]
      nextPlayers = currentPlayers
        .filter((member) => member.id !== avoidMemberId)
        .concat(replacement)
    }

    const usedHeroIds = new Set(stored.usedHeroIds ?? [])
    const heroes: any[] = require('../assets/data/heroes.json')
    if (heroes.filter((hero: any) => !usedHeroIds.has(hero.id)).length < nextPlayers.length) {
      await interaction.followUp({ content: t('group.fearlessNoHeroesLeft'), ephemeral: true })
      return
    }

    const shuffledPlayers = GroupHandler._shuffle(nextPlayers)
    const teamA = shuffledPlayers.slice(0, teamSize)
    const teamB = shuffledPlayers.slice(teamSize)

    stored.teamA = teamA
    stored.teamB = teamB
    const group = activeGroups.get(channelId)
    if (group) {
      group.members = shuffledPlayers
    }

    await GroupHandler._assignHeroesToTeams(interaction, teamA, teamB, {
      titleKey: 'group.fearlessTitle',
      blockedHeroIds: usedHeroIds,
    })
  }

  private static async _randomTeams(interaction: any, group: Group) {
    const shuffled = GroupHandler._shuffle(group.members)
    const half = group.size  // exactly size players per team
    const teamA = shuffled.slice(0, half)
    const teamB = shuffled.slice(half)

    // Persist for the move-to-channels button
    lastTeams.set(interaction.channel.id, { teamA, teamB })

    const embed = new EmbedBuilder()
      .setColor(0x3071f7)
      .setTitle(t('group.btnRandomTeams'))
      .addFields(
        {
          name: t('group.teamATitle'),
          value: teamA.map((m, i) => `${i + 1}. ${m.name}`).join('\n'),
          inline: true,
        },
        {
          name: t('group.teamBTitle'),
          value: teamB.map((m, i) => `${i + 1}. ${m.name}`).join('\n'),
          inline: true,
        }
      )

    const moveRow = new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId('group_split_channels')
        .setLabel(t('group.btnMoveChannels'))
        .setStyle(ButtonStyle.Secondary)
    )

    await interaction.channel.send({ embeds: [embed], components: [moveRow] })
  }

  private static async _randomTeamsHeroes(interaction: any, group: Group) {
    const shuffledMembers = GroupHandler._shuffle(group.members)
    const half = group.size
    const teamA = shuffledMembers.slice(0, half)
    const teamB = shuffledMembers.slice(half)
    // Persist for the move-to-channels button
    lastTeams.set(interaction.channel.id, { teamA, teamB })
    await GroupHandler._assignHeroesToTeams(interaction, teamA, teamB)
  }

  private static async _assignHeroesToTeams(
    interaction: any,
    teamA: { id: string; name: string }[],
    teamB: { id: string; name: string }[],
    options?: {
      titleKey?: string
      blockedHeroIds?: Set<number>
    }
  ) {
    const heroes: any[] = require('../assets/data/heroes.json')
    const availableHeroes = heroes.filter((hero: any) => !options?.blockedHeroIds?.has(hero.id))
    const rolesA = ROLES.slice(0, teamA.length)
    const rolesB = ROLES.slice(0, teamB.length)
    const allRoles = rolesA  // same for both teams
    const size = teamA.length

    // ── Try AI hero assignment ──────────────────────────────────────────
    let assignA: { member: typeof teamA[0]; role: string; hero: any }[] | null = null
    let assignB: { member: typeof teamB[0]; role: string; hero: any }[] | null = null

    try {
      const prompt = heroPickPrompt({ size, roles: allRoles, heroPool: availableHeroes })
      const raw = await askAI(prompt, 300, 0.4)

      if (raw) {
        // Extract JSON — strip any markdown fences the model might add
        const jsonMatch = raw.match(/\{[\s\S]*\}/)
        if (jsonMatch) {
          const parsed = JSON.parse(jsonMatch[0]) as { teamA: string[]; teamB: string[] }

          if (
            Array.isArray(parsed.teamA) && parsed.teamA.length === size &&
            Array.isArray(parsed.teamB) && parsed.teamB.length === size
          ) {
            // Match returned names to hero objects (case-insensitive)
            const findHero = (name: string) =>
              availableHeroes.find((h: any) =>
                h.localized_name.toLowerCase() === name.toLowerCase() ||
                h.name.toLowerCase() === name.toLowerCase()
              )

            const heroesA = parsed.teamA.map(findHero)
            const heroesB = parsed.teamB.map(findHero)

            // Only accept if every name resolved and there are no duplicates
            const allFound = [...heroesA, ...heroesB].every(Boolean)
            const ids = [...heroesA, ...heroesB].map((h: any) => h?.id)
            const noDups = new Set(ids).size === ids.length

            if (allFound && noDups) {
              assignA = teamA.map((m, i) => ({ member: m, role: rolesA[i], hero: heroesA[i] }))
              assignB = teamB.map((m, i) => ({ member: m, role: rolesB[i], hero: heroesB[i] }))
              console.log('[GroupHandler] AI hero assignment succeeded')
            } else {
              console.warn('[GroupHandler] AI returned unknown/duplicate heroes, falling back')
            }
          }
        }
      }
    } catch (err: any) {
      console.warn('[GroupHandler] AI hero pick failed, using fallback:', err?.message ?? err)
    }

    // ── Fallback: role-based random pick ───────────────────────────────
    if (!assignA || !assignB) {
      const usedHeroIds = new Set<number>()

      const pickHeroForRole = (roleName: string) => {
        const preferred = ROLE_PREFERRED_HERO_ROLES[roleName] ?? []
        const available = availableHeroes.filter((h: any) => !usedHeroIds.has(h.id))
        const matching = available.filter((h: any) =>
          h.roles.some((r: string) => preferred.includes(r))
        )
        const pool = matching.length > 0 ? matching : available
        const hero = pool[Math.floor(Math.random() * pool.length)]
        usedHeroIds.add(hero.id)
        return hero
      }

      assignA = teamA.map((m, i) => ({ member: m, role: rolesA[i], hero: pickHeroForRole(rolesA[i]) }))
      assignB = teamB.map((m, i) => ({ member: m, role: rolesB[i], hero: pickHeroForRole(rolesB[i]) }))
    }

    const heroImg = (name: string) =>
      `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${name}.png`

    const embeds: EmbedBuilder[] = []

    // Team A embeds (blue)
    assignA!.forEach((a, i) => {
      const e = new EmbedBuilder()
        .setColor(0x5865f2)
        .setThumbnail(heroImg(a.hero.name))
        .setDescription(`**${a.role}** — ${a.member.name}\n↳ **${a.hero.localized_name}**`)
      if (i === 0) {
        e.setTitle(t(options?.titleKey ?? 'group.btnRandomTeamsHeroes'))
        e.setAuthor({ name: `🔵 ${t('group.teamATitle')}` })
      }
      embeds.push(e)
    })

    // Team B embeds (red)
    assignB!.forEach((a, i) => {
      const e = new EmbedBuilder()
        .setColor(0xed4245)
        .setThumbnail(heroImg(a.hero.name))
        .setDescription(`**${a.role}** — ${a.member.name}\n↳ **${a.hero.localized_name}**`)
      if (i === 0) {
        e.setAuthor({ name: `🔴 ${t('group.teamBTitle')}` })
      }
      embeds.push(e)
    })

    // Reset re-roll votes whenever new heroes are assigned
    rerollVotes.delete(interaction.channel.id)

    const stored = lastTeams.get(interaction.channel.id)
    if (stored) {
      const assignedHeroIds = [...assignA!, ...assignB!].map((assignment) => assignment.hero.id)
      stored.usedHeroIds = Array.from(new Set([...(stored.usedHeroIds ?? []), ...assignedHeroIds]))
    }

    const actionRow = new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId('group_reroll_heroes')
        .setLabel(t('group.btnReroll'))
        .setStyle(ButtonStyle.Primary)
    )
    if (stored?.autoGroup) {
      actionRow.addComponents(
        new ButtonBuilder()
          .setCustomId('group_fearless_prompt')
          .setLabel(t('group.btnFearless'))
          .setStyle(ButtonStyle.Danger)
      )
    }
    actionRow.addComponents(
      new ButtonBuilder()
        .setCustomId('group_split_channels')
        .setLabel(t('group.btnMoveChannels'))
        .setStyle(ButtonStyle.Secondary)
    )

    await interaction.channel.send({ embeds, components: [actionRow] })
  }

  private static _isPublicVoiceChannel(channel: any, guild: any) {
    if (!channel || channel.type !== ChannelType.GuildVoice) return false
    if (channel.id === guild.afkChannelId) return false
    if (channel.userLimit > 0 && channel.members.size >= channel.userLimit) return false

    const everyonePermissions = channel.permissionsFor(guild.roles.everyone)
    return Boolean(
      everyonePermissions?.has(PermissionFlagsBits.ViewChannel) &&
      everyonePermissions?.has(PermissionFlagsBits.Connect)
    )
  }

  // ─── Voice channel splitter ───────────────────────────────────────────────
  /**
   * After teams are decided, move Team A to a second voice channel.
   * Team B (and any extra spectators) stays in the home channel.
   * If all members are offline/not in voice, silently skips.
   */
  private static async _splitVoiceChannels(
    interaction: any,
    teamA: { id: string; name: string }[],
    teamB: { id: string; name: string }[]
  ) {
    const guild = interaction.guild
    if (!guild) return

    // Count how many group members are in each voice channel to find the "lobby"
    const channelCounts = new Map<string, number>()
    const allMembers = [...teamA, ...teamB]
    for (const m of allMembers) {
      const guildMember = guild.members.cache.get(m.id)
      const vcId = guildMember?.voice?.channelId
      if (vcId) channelCounts.set(vcId, (channelCounts.get(vcId) || 0) + 1)
    }

    if (channelCounts.size === 0) return // nobody in a voice channel — skip silently

    // The channel with the most group members is the "home" channel
    let homeChannelId = ''
    let maxCount = 0
    for (const [id, count] of channelCounts) {
      if (count > maxCount) { maxCount = count; homeChannelId = id }
    }

    const homeChannel = guild.channels.cache.get(homeChannelId) as any
    if (!homeChannel) return

    const otherChannel = guild.channels.cache
      .filter((ch: any) =>
        ch.id !== homeChannelId && GroupHandler._isPublicVoiceChannel(ch, guild)
      )
      .sort((a: any, b: any) => {
        const aSameCategory = a.parentId === homeChannel.parentId ? 1 : 0
        const bSameCategory = b.parentId === homeChannel.parentId ? 1 : 0
        if (aSameCategory !== bSameCategory) return bSameCategory - aSameCategory
        return (a.rawPosition ?? 0) - (b.rawPosition ?? 0)
      })
      .first() as any

    if (!otherChannel) {
      await interaction.channel.send(t('group.noSecondChannel'))
      return
    }

    // Move Team A to the other channel; Team B + spectators stay in home channel
    const moved: string[] = []
    const failed: string[] = []
    for (const m of teamA) {
      try {
        const guildMember = guild.members.cache.get(m.id)
        if (guildMember?.voice?.channelId) {
          await guildMember.voice.setChannel(otherChannel)
          moved.push(m.name)
        }
      } catch {
        failed.push(m.name)
      }
    }

    if (moved.length === 0 && failed.length === 0) return // nobody was in voice

    const lines = [
      t('group.splitTeamA', { channel: otherChannel.name }),
      t('group.splitTeamB', { channel: homeChannel.name }),
    ]
    if (failed.length) lines.push(t('group.splitFailed', { names: failed.join(', ') }))

    const embed = new EmbedBuilder()
      .setColor(0x5865f2)
      .setTitle(t('group.splitTitle'))
      .setDescription(lines.join('\n'))

    await interaction.channel.send({ embeds: [embed] })
  }

  static getActive(channelId: string): Group | undefined {
    return activeGroups.get(channelId)
  }

  // ─── !autox2 / !autox4 / !autox5 ─────────────────────────────────────────
  /**
   * Reads the caller's voice channel, excludes any @mentioned users,
   * picks exactly (size * 2) players, randomizes teams immediately,
   * and posts the result with [⚔️ Assign Heroes] and [🔀 Move to Channels] buttons.
   */
  static async autoGroup(message: Message, size: 2 | 4 | 5) {
    const totalSlots = size * 2
    const voiceMember = message.member

    if (!voiceMember?.voice?.channel) {
      message.reply(t('group.autoNotInVoice', { size }))
      return
    }

    const voiceChannel = voiceMember.voice.channel
    const excludedIds = new Set(message.mentions.users.map((u) => u.id))

    const candidates = voiceChannel.members
      .filter((m: GuildMember) => !m.user.bot && !excludedIds.has(m.id))
      .map((m: GuildMember) => ({ id: m.id, name: m.displayName }))

    if (candidates.length < totalSlots) {
      message.reply(t('group.autoNotEnough', { need: totalSlots, found: candidates.length }))
      return
    }

    const shuffled = GroupHandler._shuffle(candidates).slice(0, totalSlots)
    const teamA = shuffled.slice(0, size)
    const teamB = shuffled.slice(size)

    const channelId = message.channel.id

    // Store as pending — teams are committed only after the trigger user confirms
    pendingAutoGroups.set(channelId, {
      size,
      candidates,
      teamA,
      teamB,
      triggerUserId: message.author.id,
      sourceVoiceChannelId: voiceChannel.id,
      excludedIds: Array.from(excludedIds),
    })

    const previewEmbed = new EmbedBuilder()
      .setColor(0xffa500)
      .setTitle(`👁️ Preview — Auto x${size}`)
      .setDescription(t('group.autoPreviewDescription'))
      .addFields(
        { name: t('group.teamATitle'), value: teamA.map((m, i) => `${i + 1}. ${m.name}`).join('\n'), inline: true },
        { name: t('group.teamBTitle'), value: teamB.map((m, i) => `${i + 1}. ${m.name}`).join('\n'), inline: true }
      )

    const row = GroupHandler._buildAutoPreviewRow(channelId)

    try {
      await message.author.send({ embeds: [previewEmbed], components: [row] })
    } catch {
      pendingAutoGroups.delete(channelId)
      await message.reply(t('group.autoPreviewDmFailed'))
    }
  }

  /**
   * Called from the VoiceStateUpdate event when a user fully disconnects from voice.
   * Always removes the member; if they were creator, promotes the next member.
   */
  static async handleVoiceLeave(userId: string, client: any) {
    for (const [channelId, group] of activeGroups.entries()) {
      const memberIndex = group.members.findIndex((m) => m.id === userId)
      if (memberIndex === -1) continue

      const member = group.members[memberIndex]
      const textChannel = client.channels.cache.get(channelId) as any

      group.members.splice(memberIndex, 1)

      if (group.members.length === 0) {
        activeGroups.delete(channelId)
        console.log(`[GroupHandler] ${member.name} left voice — group empty, disbanded`)
        if (textChannel) await textChannel.send(t('group.disbanded.empty'))
        break
      }

      const wasCreator = group.creatorId === userId
      let creatorNote = ''
      if (wasCreator) {
        group.creatorId = group.members[0].id
        group.creatorName = group.members[0].name
        creatorNote = ` New creator: **${group.creatorName}**.`
      }

      console.log(`[GroupHandler] ${member.name} left voice — removed from x${group.size} group`)
      if (textChannel) {
        await textChannel.send(t('group.voiceLeft', { name: member.name }) + creatorNote)
      }
      break
    }
  }
}
